export interface DSAQuestion {
  id: string
  title: string
  difficulty: "Easy" | "Medium" | "Hard"
  topic: string
  description: string
  xp: number
  companies: string[]
  leetcodeUrl: string
  solved: boolean
  frequency: "Common" | "Medium" | "Rare"
}

export const DSA_QUESTIONS: DSAQuestion[] = [
  // Arrays - Easy
  {
    id: "arr-1",
    title: "Two Sum",
    difficulty: "Easy",
    topic: "Arrays",
    description: "Find two numbers that add up to a target value",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/two-sum/",
    solved: true,
    frequency: "Common",
  },
  {
    id: "arr-2",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    topic: "Arrays",
    description: "Find maximum profit from buying and selling stocks once",
    xp: 75,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-3",
    title: "Contains Duplicate",
    difficulty: "Easy",
    topic: "Arrays",
    description: "Check if array contains any duplicate values",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/contains-duplicate/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-4",
    title: "Valid Parentheses",
    difficulty: "Easy",
    topic: "Arrays",
    description: "Check if parentheses are balanced correctly",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/valid-parentheses/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-5",
    title: "Majority Element",
    difficulty: "Easy",
    topic: "Arrays",
    description: "Find element appearing more than n/2 times",
    xp: 75,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/majority-element/",
    solved: false,
    frequency: "Common",
  },

  // Arrays - Medium
  {
    id: "arr-6",
    title: "Product of Array Except Self",
    difficulty: "Medium",
    topic: "Arrays",
    description: "Return array where each element is product of all other elements",
    xp: 100,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/product-of-array-except-self/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-7",
    title: "Container With Most Water",
    difficulty: "Medium",
    topic: "Arrays",
    description: "Find two lines that form a container with maximum area",
    xp: 100,
    companies: ["Google", "Meta", "Amazon"],
    leetcodeUrl: "https://leetcode.com/problems/container-with-most-water/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-8",
    title: "3Sum",
    difficulty: "Medium",
    topic: "Arrays",
    description: "Find all unique triplets that sum to zero",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/3sum/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-9",
    title: "Rotate Array",
    difficulty: "Medium",
    topic: "Arrays",
    description: "Rotate array elements to the right by k steps",
    xp: 100,
    companies: ["Google", "Amazon", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/rotate-array/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "arr-10",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    topic: "Arrays",
    description: "Find target value in rotated sorted array",
    xp: 125,
    companies: ["Google", "Microsoft", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    solved: false,
    frequency: "Common",
  },

  // Arrays - Hard
  {
    id: "arr-11",
    title: "Merge K Sorted Lists",
    difficulty: "Hard",
    topic: "Arrays",
    description: "Merge multiple sorted arrays into one sorted array",
    xp: 200,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/merge-k-sorted-lists/",
    solved: false,
    frequency: "Medium",
  },
  {
    id: "arr-12",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topic: "Arrays",
    description: "Calculate how much water can be trapped after raining",
    xp: 225,
    companies: ["Google", "Microsoft", "Amazon"],
    leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/",
    solved: false,
    frequency: "Medium",
  },
  {
    id: "arr-13",
    title: "First Missing Positive",
    difficulty: "Hard",
    topic: "Arrays",
    description: "Find the smallest missing positive integer",
    xp: 200,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/first-missing-positive/",
    solved: false,
    frequency: "Medium",
  },

  // Linked Lists - Easy
  {
    id: "ll-1",
    title: "Reverse Linked List",
    difficulty: "Easy",
    topic: "Linked Lists",
    description: "Reverse the order of elements in a linked list",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/",
    solved: true,
    frequency: "Common",
  },
  {
    id: "ll-2",
    title: "Linked List Cycle",
    difficulty: "Easy",
    topic: "Linked Lists",
    description: "Detect if a linked list has a cycle",
    xp: 75,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "ll-3",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topic: "Linked Lists",
    description: "Merge two sorted linked lists into one",
    xp: 50,
    companies: ["Amazon", "Google", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/merge-two-sorted-lists/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "ll-4",
    title: "Palindrome Linked List",
    difficulty: "Easy",
    topic: "Linked Lists",
    description: "Check if linked list is palindrome",
    xp: 75,
    companies: ["Google", "Amazon", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/palindrome-linked-list/",
    solved: false,
    frequency: "Common",
  },

  // Linked Lists - Medium
  {
    id: "ll-5",
    title: "LRU Cache",
    difficulty: "Medium",
    topic: "Linked Lists",
    description: "Design and implement LRU (Least Recently Used) Cache",
    xp: 150,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/lru-cache/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "ll-6",
    title: "Add Two Numbers",
    difficulty: "Medium",
    topic: "Linked Lists",
    description: "Add two numbers represented as linked lists",
    xp: 125,
    companies: ["Amazon", "Google", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/add-two-numbers/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "ll-7",
    title: "Remove Nth Node From End",
    difficulty: "Medium",
    topic: "Linked Lists",
    description: "Remove n-th node from end of linked list",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    solved: false,
    frequency: "Common",
  },

  // Linked Lists - Hard
  {
    id: "ll-8",
    title: "Reverse Nodes in K-Group",
    difficulty: "Hard",
    topic: "Linked Lists",
    description: "Reverse every k nodes in a linked list",
    xp: 200,
    companies: ["Google", "Microsoft", "Amazon"],
    leetcodeUrl: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    solved: false,
    frequency: "Medium",
  },

  // Strings - Easy
  {
    id: "str-1",
    title: "Valid Palindrome",
    difficulty: "Easy",
    topic: "Strings",
    description: "Check if a string is a palindrome ignoring spaces and punctuation",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/valid-palindrome/",
    solved: true,
    frequency: "Common",
  },
  {
    id: "str-2",
    title: "Reverse String",
    difficulty: "Easy",
    topic: "Strings",
    description: "Reverse a string in place",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/reverse-string/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "str-3",
    title: "Implement strStr",
    difficulty: "Easy",
    topic: "Strings",
    description: "Find first occurrence of substring in string",
    xp: 75,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/implement-strstr/",
    solved: false,
    frequency: "Common",
  },

  // Strings - Medium
  {
    id: "str-4",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    topic: "Strings",
    description: "Find the length of longest substring without duplicate characters",
    xp: 100,
    companies: ["Google", "Amazon", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "str-5",
    title: "Group Anagrams",
    difficulty: "Medium",
    topic: "Strings",
    description: "Group strings that are anagrams together",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/group-anagrams/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "str-6",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    topic: "Strings",
    description: "Find longest substring that is a palindrome",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-substring/",
    solved: false,
    frequency: "Common",
  },

  // Strings - Hard
  {
    id: "str-7",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topic: "Strings",
    description: "Find minimum window substring containing all characters",
    xp: 200,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "str-8",
    title: "Word Ladder II",
    difficulty: "Hard",
    topic: "Strings",
    description: "Find all shortest transformation sequences between words",
    xp: 225,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/word-ladder-ii/",
    solved: false,
    frequency: "Rare",
  },

  // Trees - Easy
  {
    id: "tree-1",
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topic: "Trees",
    description: "Invert all nodes of a binary tree",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/invert-binary-tree/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "tree-2",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topic: "Trees",
    description: "Find the maximum depth of a binary tree",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "tree-3",
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    topic: "Trees",
    description: "Check if binary tree is height-balanced",
    xp: 75,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/balanced-binary-tree/",
    solved: false,
    frequency: "Common",
  },

  // Trees - Medium
  {
    id: "tree-4",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    topic: "Trees",
    description: "Validate if a binary tree is a valid BST",
    xp: 100,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "tree-5",
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    topic: "Trees",
    description: "Traverse binary tree level by level",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "tree-6",
    title: "Lowest Common Ancestor",
    difficulty: "Medium",
    topic: "Trees",
    description: "Find lowest common ancestor of two nodes",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "tree-7",
    title: "Path Sum",
    difficulty: "Medium",
    topic: "Trees",
    description: "Check if tree has path with given sum",
    xp: 100,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/path-sum/",
    solved: false,
    frequency: "Common",
  },

  // Trees - Hard
  {
    id: "tree-8",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    topic: "Trees",
    description: "Find the maximum path sum in a binary tree",
    xp: 200,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    solved: false,
    frequency: "Medium",
  },
  {
    id: "tree-9",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    topic: "Trees",
    description: "Serialize binary tree to string and deserialize back",
    xp: 225,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    solved: false,
    frequency: "Medium",
  },

  // Graphs - Medium
  {
    id: "graph-1",
    title: "Number of Islands",
    difficulty: "Medium",
    topic: "Graphs",
    description: "Count the number of islands in a 2D grid",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/number-of-islands/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "graph-2",
    title: "Course Schedule",
    difficulty: "Medium",
    topic: "Graphs",
    description: "Determine if course prerequisites can be completed",
    xp: 100,
    companies: ["Amazon", "Google", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/course-schedule/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "graph-3",
    title: "Clone Graph",
    difficulty: "Medium",
    topic: "Graphs",
    description: "Create a deep copy of a graph",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/clone-graph/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "graph-4",
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    topic: "Graphs",
    description: "Find cells that water can flow to both oceans",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    solved: false,
    frequency: "Medium",
  },

  // Graphs - Hard
  {
    id: "graph-5",
    title: "Word Ladder",
    difficulty: "Hard",
    topic: "Graphs",
    description: "Find shortest transformation sequence between words",
    xp: 200,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/word-ladder/",
    solved: false,
    frequency: "Medium",
  },
  {
    id: "graph-6",
    title: "Alien Dictionary",
    difficulty: "Hard",
    topic: "Graphs",
    description: "Derive character order from sorted alien dictionary",
    xp: 225,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/alien-dictionary/",
    solved: false,
    frequency: "Rare",
  },

  // Dynamic Programming - Easy
  {
    id: "dp-1",
    title: "Climbing Stairs",
    difficulty: "Easy",
    topic: "Dynamic Programming",
    description: "Count ways to climb n stairs taking 1 or 2 steps",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "dp-2",
    title: "Fibonacci Number",
    difficulty: "Easy",
    topic: "Dynamic Programming",
    description: "Calculate the n-th fibonacci number",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/fibonacci-number/",
    solved: false,
    frequency: "Common",
  },

  // Dynamic Programming - Medium
  {
    id: "dp-3",
    title: "House Robber",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    description: "Determine maximum money that can be robbed",
    xp: 100,
    companies: ["Amazon", "Google", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/house-robber/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "dp-4",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    description: "Find the length of longest increasing subsequence",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "dp-5",
    title: "Coin Change",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    description: "Find minimum coins needed to make amount",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/coin-change/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "dp-6",
    title: "Decode Ways",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    description: "Count number of ways to decode a string",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/decode-ways/",
    solved: false,
    frequency: "Common",
  },

  // Dynamic Programming - Hard
  {
    id: "dp-7",
    title: "Edit Distance",
    difficulty: "Hard",
    topic: "Dynamic Programming",
    description: "Calculate minimum edits needed to transform one string to another",
    xp: 200,
    companies: ["Google", "Amazon", "Microsoft"],
    leetcodeUrl: "https://leetcode.com/problems/edit-distance/",
    solved: false,
    frequency: "Medium",
  },
  {
    id: "dp-8",
    title: "Regular Expression Matching",
    difficulty: "Hard",
    topic: "Dynamic Programming",
    description: "Implement regular expression matching with . and *",
    xp: 225,
    companies: ["Google", "Microsoft", "Amazon"],
    leetcodeUrl: "https://leetcode.com/problems/regular-expression-matching/",
    solved: false,
    frequency: "Medium",
  },

  // Hashing - Easy
  {
    id: "hash-1",
    title: "Valid Anagram",
    difficulty: "Easy",
    topic: "Hashing",
    description: "Determine if two strings are anagrams",
    xp: 50,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/valid-anagram/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "hash-2",
    title: "Isomorphic Strings",
    difficulty: "Easy",
    topic: "Hashing",
    description: "Check if two strings are isomorphic",
    xp: 75,
    companies: ["Google", "Amazon", "Apple"],
    leetcodeUrl: "https://leetcode.com/problems/isomorphic-strings/",
    solved: false,
    frequency: "Common",
  },

  // Hashing - Medium
  {
    id: "hash-3",
    title: "Group Anagrams",
    difficulty: "Medium",
    topic: "Hashing",
    description: "Group strings that are anagrams together",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/group-anagrams/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "hash-4",
    title: "Intersection of Two Arrays II",
    difficulty: "Medium",
    topic: "Hashing",
    description: "Find intersection of two arrays",
    xp: 100,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/intersection-of-two-arrays-ii/",
    solved: false,
    frequency: "Common",
  },
  {
    id: "hash-5",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topic: "Hashing",
    description: "Find k most frequent elements in array",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/",
    solved: false,
    frequency: "Common",
  },

  // Additional Topics
  {
    id: "heap-1",
    title: "Kth Largest Element",
    difficulty: "Medium",
    topic: "Hashing",
    description: "Find kth largest element in unsorted array",
    xp: 125,
    companies: ["Google", "Amazon", "Meta"],
    leetcodeUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    solved: false,
    frequency: "Common",
  },
]

export const TOPICS = [
  "All Topics",
  "Arrays",
  "Linked Lists",
  "Strings",
  "Trees",
  "Graphs",
  "Dynamic Programming",
  "Hashing",
]
