import type { DebugSession, SessionReport } from "@/lib/types/session-reports"

export function generateSessionReport(session: DebugSession, language: "english" | "hindi" = "english"): SessionReport {
  const langText = language === "english"

  const keyLearnings = []
  if (session.errorType.includes("Type"))
    keyLearnings.push(langText ? "Understanding type safety and operations" : "Type safety और operations को समझना")
  if (session.errorType.includes("Reference"))
    keyLearnings.push(langText ? "Variable scope and declaration" : "Variable scope और declaration")
  if (session.errorType.includes("Loop"))
    keyLearnings.push(langText ? "Loop conditions and control flow" : "Loop conditions और control flow")

  const nextSteps = []
  if (session.complexity === "High")
    nextSteps.push(
      langText
        ? "Practice breaking complex problems into smaller steps"
        : "Complex problems को छोटे steps में break करने का practice करें",
    )
  nextSteps.push(
    langText
      ? "Review similar error patterns from past sessions"
      : "पिछली debugging sessions से similar patterns review करें",
  )

  return {
    session,
    summary: langText
      ? `You debugged a ${session.complexity.toLowerCase()} complexity ${session.language} code and fixed a ${session.errorType}.`
      : `आपने एक ${session.complexity.toLowerCase()} complexity ${session.language} code को debug किया और ${session.errorType} को fix किया।`,
    keyLearnings:
      keyLearnings.length > 0
        ? keyLearnings
        : [langText ? "Code debugging fundamentals" : "Code debugging के fundamentals"],
    nextSteps,
    complexityAnalysis: {
      current: session.complexity,
      explanation: langText
        ? "Review your code structure and consider refactoring if needed"
        : "अपने code structure को review करें और ज़रूरत पड़ने पर refactor करें",
    },
  }
}

export function generateDownloadableReport(report: SessionReport, language: "english" | "hindi" = "english"): string {
  const langText = language === "english"

  const markdown = `# ${langText ? "Debug Session Report" : "Debug Session Report"}
Date: ${report.session.timestamp.toLocaleDateString()}

## Summary
${report.summary}

## Error Details
- **Error Type**: ${report.session.errorType}
- **Language**: ${report.session.language}
- **Complexity**: ${report.session.complexity}
- **Time Spent**: ${Math.round(report.session.timeSpent / 60)} minutes

## Key Learnings
${report.keyLearnings.map((learning) => `- ${learning}`).join("\n")}

## Next Steps
${report.nextSteps.map((step) => `- ${step}`).join("\n")}

## Code Analysis
### Original Code
\`\`\`
${report.session.code}
\`\`\`

### Complexity Analysis
${report.complexityAnalysis.explanation}

---
Generated by CodeTutor | Keep learning, keep growing!
`

  return markdown
}

export function checkAchievements(
  totalSessions: number,
  totalErrors: number,
): { title: string; description: string; icon: string }[] {
  const achievements = []

  if (totalSessions === 1)
    achievements.push({
      title: "First Debug",
      description: "Complete your first debugging session",
      icon: "🚀",
    })
  if (totalSessions === 5)
    achievements.push({
      title: "Debugger",
      description: "Complete 5 debugging sessions",
      icon: "🔧",
    })
  if (totalSessions === 10)
    achievements.push({
      title: "Master Debugger",
      description: "Complete 10 debugging sessions",
      icon: "🎯",
    })
  if (totalErrors >= 5)
    achievements.push({
      title: "Error Solver",
      description: "Fix 5 different types of errors",
      icon: "💡",
    })

  return achievements
}
